{{- if .Values.configMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "custom-deployment.fullname" . }}
    labels:
        {{- include "custom-deployment.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMap.data }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end -}}
