{{- if .Values.dockerconfigjson }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: {{ include "custom-deployment.dockerconfig-secret-name" . }}
    labels:
        {{- include "custom-deployment.labels" . | nindent 4 }}
    annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/sync-wave: '1'
data:
    .dockerconfigjson: "{{ .Values.dockerconfigjson }}"
{{- end }}