{{- if and .Values.ingress.enabled .Values.ingress.forwardAuth.enabled }}
apiVersion: traefik.io/v1alpha1 # Use traefik.containo.us/v1alpha1 if using older Traefik
kind: Middleware
metadata:
  # Use the helper for the Middleware resource name
  name: {{ .Values.ingress.forwardAuth.name | quote }}
  # Middleware MUST be in the same namespace as the Ingress that uses it
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "custom-deployment.labels" . | nindent 4 }}
spec:
  forwardAuth:
    # Required fields from values.yaml
    address: {{ .Values.ingress.forwardAuth.address | quote }}
    trustForwardHeader: {{ .Values.ingress.forwardAuth.trustForwardHeader | default true }}

    # Conditionally add authRequestHeaders if provided in values
    {{- if .Values.ingress.forwardAuth.authRequestHeaders }}
    authRequestHeaders:
      {{- toYaml .Values.ingress.forwardAuth.authRequestHeaders | nindent 6 }}
    {{- end }}
{{- end }}