{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom-deployment.fullname" . }}
  labels:
    {{- include "custom-deployment.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "custom-deployment.selectorLabels" . | nindent 4 }}
    module: main-app
{{- end }}
