{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "custom-deployment.serviceAccountName" . }}
  labels:
    {{- include "custom-deployment.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- if .Values.roles -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "custom-deployment.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "custom-deployment.labels" . | nindent 4 }}
rules:
{{- range $rule := .Values.roles }}
- apiGroups: [{{ $rule.apiGroup }}]
  resources: ["{{ $rule.resources | join ", " }}"]
  verbs: ["{{ $rule.verbs | join ", " }}"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "custom-deployment.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "custom-deployment.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "custom-deployment.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "custom-deployment.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
